import { useState } from "react";
import { X, Loader2, FileText, Clock, Users, MessageSquare, Mic } from "lucide-react";

const CallSummary = ({ summary, isGenerating, onClose, callDuration, participants, transcript, onGenerateSummary }) => {
  const [isExpanded, setIsExpanded] = useState(true);
  const [showTranscript, setShowTranscript] = useState(false);

  const formatDuration = (seconds) => {
    if (!seconds) return "0:00";
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, "0")}`;
  };

  if (!isExpanded) {
    return (
      <button
        onClick={() => setIsExpanded(true)}
        className="fixed bottom-24 right-6 bg-primary text-primary-content p-4 rounded-full shadow-lg hover:scale-105 transition-transform z-50"
      >
        <FileText size={24} />
      </button>
    );
  }

  return (
    <div className="fixed bottom-24 right-6 w-96 bg-base-200 rounded-lg shadow-2xl z-50 max-h-[500px] flex flex-col">
      {/* Header */}
      <div className="flex items-center justify-between p-4 border-b border-base-300">
        <div className="flex items-center gap-2">
          <FileText className="text-primary" size={20} />
          <h3 className="font-semibold">Call Summary</h3>
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setIsExpanded(false)}
            className="btn btn-ghost btn-sm btn-circle"
          >
            _
          </button>
          <button
            onClick={onClose}
            className="btn btn-ghost btn-sm btn-circle"
          >
            <X size={18} />
          </button>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {/* Call Info */}
        <div className="flex items-center gap-4 text-sm text-base-content/70">
          {callDuration && (
            <div className="flex items-center gap-1">
              <Clock size={16} />
              <span>{formatDuration(callDuration)}</span>
            </div>
          )}
          {participants && participants.length > 0 && (
            <div className="flex items-center gap-1">
              <Users size={16} />
              <span>{participants.length} participants</span>
            </div>
          )}
        </div>

        {/* Transcript Toggle & Manual Summary Button */}
        <div className="flex items-center justify-between text-xs gap-2">
          {transcript && (
            <button
              onClick={() => setShowTranscript(!showTranscript)}
              className="flex items-center gap-1 text-primary hover:underline"
            >
              <MessageSquare size={14} />
              {showTranscript ? "Hide" : "Show"} Transcript ({transcript.length} chars)
            </button>
          )}
          {transcript && transcript.length > 50 && !isGenerating && (
            <button
              onClick={onGenerateSummary}
              className="btn btn-xs btn-primary gap-1"
            >
              <Mic size={12} />
              Generate Summary
            </button>
          )}
        </div>

        {/* Transcript Display */}
        {showTranscript && transcript && (
          <div className="bg-base-100 rounded-lg p-3 max-h-32 overflow-y-auto">
            <p className="text-xs text-base-content/70 leading-relaxed">{transcript}</p>
          </div>
        )}

        {/* Summary Content */}
        {isGenerating ? (
          <div className="flex flex-col items-center justify-center py-8 gap-3">
            <Loader2 className="animate-spin text-primary" size={32} />
            <p className="text-sm text-base-content/70">Generating AI summary...</p>
            <p className="text-xs text-base-content/50">This may take 20-30 seconds...</p>
          </div>
        ) : summary ? (
          <div className="space-y-3">
            <div className="bg-base-300 rounded-lg p-4">
              <p className="text-sm leading-relaxed">{summary}</p>
            </div>
            <p className="text-xs text-base-content/50 italic">
              Generated by AI • May not be 100% accurate
            </p>
          </div>
        ) : (
          <div className="text-center py-8 text-base-content/50">
            <FileText size={48} className="mx-auto mb-3 opacity-30" />
            <p className="text-sm">No summary available yet</p>
            <p className="text-xs mt-1">
              {transcript ? "Keep talking... Summary will generate in 30 seconds" : "Start talking to begin transcription"}
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default CallSummary;

